branch:py3.8-fix-for-tracing
